"""
Example taken from the book:
    Przemyslaw Prusinkiewicz, Aristid Lindenmayer –
    [The Algorithmic Beauty of Plants PDF version available here for free Archived 2021-04-10 at the Wayback Machine]
    (https://en.wikipedia.org/wiki/The_Algorithmic_Beauty_of_Plants)

Section 1.4 Synthesis of DOL-systems
"""

from l_system.base import Lsystem
from l_system.rendering.renderer import LSystemRenderer
from l_system.rendering.turtle import TurtleConfiguration


class DragonCurve(Lsystem):
    """Figure 1.10: Examples of curves generated by edge-rewriting L-systems: (a) the dragon curve."""

    axiom = 'A'
    productions = {'A': 'A+B+', 'B': '-A-B'}
    recursions = 10


if __name__ == '__main__':
    lsystem = DragonCurve()
    turtle_conf = TurtleConfiguration(angle=90, turtle_move_mapper={'A': 'F', 'B': 'F'}, initial_heading_angle=90)
    renderer = LSystemRenderer(lsystem, turtle_conf)
    renderer.draw()
