"""
Example taken from the book:
    Przemyslaw Prusinkiewicz, Aristid Lindenmayer –
    [The Algorithmic Beauty of Plants PDF version available here for free Archived 2021-04-10 at the Wayback Machine]
    (https://en.wikipedia.org/wiki/The_Algorithmic_Beauty_of_Plants)

Section 1.4 Synthesis of DOL-systems
"""

from l_system.base import Lsystem
from l_system.rendering.renderer import LSystemRenderer
from l_system.rendering.turtle import TurtleConfiguration


class HexagonalGosperCurve(Lsystem):
    """From figure 1.11a: Example of FASS curves generated by edge-rewriting L-Systems: Hex Gosper curve."""

    axiom = 'A'
    productions = {'A': 'A+B++B-A--AA-B+', 'B': '-A+BB++B+A--A-B'}
    recursions = 4


if __name__ == '__main__':
    lsystem = HexagonalGosperCurve()
    turtle_conf = TurtleConfiguration(angle=60, turtle_move_mapper={'A': 'F', 'B': 'F'})
    renderer = LSystemRenderer(lsystem, turtle_conf)
    renderer.draw()
