"""
Example taken from the book:
    Przemyslaw Prusinkiewicz, Aristid Lindenmayer –
    [The Algorithmic Beauty of Plants PDF version available here for free Archived 2021-04-10 at the Wayback Machine]
    (https://en.wikipedia.org/wiki/The_Algorithmic_Beauty_of_Plants)

Section 1.4 Synthesis of DOL-systems
"""

from l_system.base import Lsystem
from l_system.rendering.renderer import LSystemRenderer
from l_system.rendering.turtle import TurtleConfiguration


class SierpinskiGask(Lsystem):
    """Figure 1.10: Examples of curves generated by edge-rewriting L-systems: (b) the Sierpinski gasket."""

    axiom = 'B'
    productions = {'A': 'B+A+B', 'B': 'A-B-A'}
    recursions = 6


if __name__ == '__main__':
    lsystem = SierpinskiGask()
    turtle_conf = TurtleConfiguration(angle=60, turtle_move_mapper={'A': 'F', 'B': 'F'})

    renderer = LSystemRenderer(lsystem, turtle_conf)
    renderer.draw()
