"""
Example taken from the book:
    Przemyslaw Prusinkiewicz, Aristid Lindenmayer –
    [The Algorithmic Beauty of Plants PDF version available here for free Archived 2021-04-10 at the Wayback Machine]
    (https://en.wikipedia.org/wiki/The_Algorithmic_Beauty_of_Plants)

Section 1.6.3 Bracketed OL-systems
"""

from l_system.base import Lsystem
from l_system.rendering.turtle import TurtleConfiguration


class BracketedOlSystemFig124a(Lsystem):
    """Figure 1.24: Examples of plant-like structures generated by bracketed OL-systems. (a) Edge-rewriting system."""

    axiom = 'F'
    productions = {
        'F': 'F[+F]F[-F]F',
    }
    recursions = 4


DEFAULT_TURTLE_CONFIG = TurtleConfiguration(angle=25.7, initial_heading_angle=90)
